name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main
      - development

permissions:
  checks: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAVERICK_NTULI }}
          projectId: laverick-ntuli
          channelId: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
